import { test, expect, type Page } from '@playwright/test';
import { csvText } from '../src/lib/csv';
async function login(page: Page, email: string) {
    await page.goto('#/login');
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('BrowserTest123!');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
}
test('organizer creates, adjusts stock, starts, pauses and exports full results', async ({ page }) => {
    await login(page, 'organizer@example.test');
    await expect(page.getByRole('heading', { name: 'Your events' })).toBeVisible();
    await page.getByRole('button', { name: 'Create event', exact: true }).click();
    await page.getByLabel('Event name').fill('Created from browser');
    await page.getByRole('button', { name: 'Create', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Created from browser' })).toBeVisible();
    await page.getByRole('link', { name: 'Switch event' }).click();
    await page.getByRole('article').filter({ hasText: 'Field activation' }).getByRole('link', { name: 'Open event' }).click();
    await page.getByRole('link', { name: 'Inventory', exact: true }).click();
    await page.getByRole('button', { name: 'Add reward' }).click();
    await page.getByLabel('Prize', { exact: true }).fill('Coffee');
    await page.getByLabel('Available units').fill('3');
    await page.getByRole('button', { name: 'Save stock' }).click();
    await expect(page.getByRole('cell', { name: '3', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Start event' }).click();
    await page.getByRole('button', { name: 'Confirm', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Pause', exact: true }).click();
    await page.getByRole('button', { name: 'Confirm', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Report', exact: true }).click();
    const download = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export claims', exact: true }).click();
    expect((await download).suggestedFilename()).toBe('event-browser-flow-claims.csv');
});
test('staff redeems once on a phone and cannot open organizer screens', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await login(page, 'staff@example.test');
    await expect(page.getByRole('heading', { name: 'Redeem a reward' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Settings', exact: true })).toHaveCount(0);
    await page.getByLabel('Redemption code').fill('ORBS-BROWSER');
    await page.getByRole('button', { name: 'Check code', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Coffee', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Redeem prize', exact: true }).click();
    await page.getByRole('button', { name: 'Confirm', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Redeemed successfully' })).toBeVisible();
    await page.getByRole('button', { name: 'Check another code' }).click();
    await page.getByLabel('Redemption code').fill('ORBS-BROWSER');
    await page.getByRole('button', { name: 'Check code', exact: true }).click();
    await expect(page.getByText('Already redeemed', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Redeem prize', exact: true })).toHaveCount(0);
    await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 375);
});
test('player has no administrative access', async ({ page }) => { await login(page, 'player@example.test'); await expect(page.getByRole('heading', { name: 'Access required' })).toBeVisible(); });
test('CSV quotes text and prevents spreadsheet formulas', () => { expect(csvText(['name'], [['=SUM(1,2)'], ['a"b']])).toBe('\uFEFF"name"\r\n"\'=SUM(1,2)"\r\n"a""b"'); });
test('map placement, move and zone save use the existing event backend', async ({ page }) => {
    await login(page, 'organizer@example.test');
    await page.goto('#/events/browser-flow/map');
    await expect(page.getByRole('button', { name: 'Place Orb', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Place Orb', exact: true }).click();
    const canvas = page.locator('.maplibregl-canvas');
    const box = await canvas.boundingBox();
    await canvas.click({ position: { x: box!.width / 2, y: box!.height / 2 } });
    await expect(page.getByRole('heading', { name: 'Orb properties' })).toBeVisible();
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Selected Orb' })).toBeVisible();
    await page.getByRole('button', { name: 'Move', exact: true }).click();
    await canvas.click({ position: { x: box!.width / 2 + 25, y: box!.height / 2 } });
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Selected Orb' })).toBeVisible();
    await page.getByRole('button', { name: 'Draw / edit zone', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Save zone', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Save zone', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Selected Orb' })).toBeVisible();
    await page.screenshot({ path: '/tmp/orbs-admin-map.png', fullPage: true });
});
