import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createHashRouter } from 'react-router-dom';
import { SessionProvider } from './lib/session';
import { App } from './App';
import './styles.css';
const client = new QueryClient();
const router = createHashRouter([{ path: '*', element: <App /> }]);
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><SessionProvider><RouterProvider router={router}/></SessionProvider></QueryClientProvider></React.StrictMode>);
